### ISSUE TITLE
hello，我用了之后有报错，能帮忙看下吗

### ISSUE THREAD

**Issue by dreamyboy** [kelvv/aliyun-sms-node#3]
{"RequestId":"05EDDD06-36E0-4A59-A2C2-62BCB079BE50","HostId":"sms.aliyuncs.com","Code":"InvalidDayuStatus.Malformed","Message":"The specified dayu status is wrongly formed."}

求帮助看下🤕

**Comment by kelvv** [comment]
接口更新了，我会尽快修复更新

**Comment by dreamyboy** [comment]
感谢！～～～～～想加个微信哈

**Comment by kelvv** [comment]
@dreamyboy  Jarvin-Guan

**Comment by kelvv** [comment]
v1.1.3 已经修复
