### ISSUE TITLE
cryto@0.03 is no longer supported

### ISSUE THREAD

**Issue by Crise420WMT** [kelvv/aliyun-sms-node#6]
when i npm install aliyun-sms-node, it appeared....

[crypto@0.0.3](.\node_modules\.1.1.3@aliyun-sms-node\node_modules\crypto) deprecate: This package is no longer supported. It's now a   built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

**Comment by kelvv** [comment]
@Crise420WMT  different running  environment have different support , so 

I think it will be ok to let it here
